theme: jekyll-theme-slate
url: "https://google-engineering-practices.translation.shuuji3.xyz"
baseurl: ""

plugins:
  - jekyll-analytics
  - jekyll-default-layout
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-titles-from-headings

jekyll_analytics:
  Umami:
    website_id: "5a967cca-9fd9-4ec7-aac7-4bc809b4d126"
    source: "https://umami.shuuji3.xyz/script.js"

